"""Generate the committed WebP assets. Requires Pillow (pip install Pillow).

Original PNGs remain the source of truth. Run after adding/changing artwork.
The browser and Vercel serve the generated files directly; no runtime build.
"""
from concurrent.futures import ThreadPoolExecutor
from hashlib import sha256
from pathlib import Path
import json
import re
from io import BytesIO
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'assets' / 'web'
OUTPUT.mkdir(exist_ok=True)


def convert(source):
    relative = source.relative_to(ROOT).as_posix()
    variants = {'full': None}
    if 'heroes' in source.parts:
        variants = {'full': None, 'thumb': (320, 400)}
    result = {}
    with Image.open(source) as original:
        for variant, size in variants.items():
            picture = original.convert('RGBA' if 'A' in original.getbands() else 'RGB')
            if size:
                picture.thumbnail(size, Image.Resampling.LANCZOS)
            buffer = BytesIO()
            picture.save(buffer, 'WEBP', quality=90 if variant == 'full' else 86, method=4)
            data = buffer.getvalue()
            digest = sha256(data).hexdigest()[:12]
            stem = relative.removeprefix('assets/').removesuffix('.png').replace('/', '-')
            path = OUTPUT / f'{stem}-{variant}.{digest}.webp'
            path.write_bytes(data)
            result[variant] = path.relative_to(ROOT).as_posix()
    return relative, result


sources = sorted((ROOT / 'assets').rglob('*.png'))
with ThreadPoolExecutor(max_workers=4) as pool:
    manifest = dict(pool.map(convert, sources))
(ROOT / 'asset-manifest.js').write_text(
    '// Generated by tools/optimize_web_assets.py; do not edit.\n'
    'window.RDFZ_ASSET_MANIFEST = ' + json.dumps(manifest, separators=(',', ':')) + ';\n'
)
# CSS uses variables so future regeneration never needs to rewrite game styles.
css = ['/* Generated by tools/optimize_web_assets.py; do not edit. */', ':root {']
used_variables = set()
for sheet in ROOT.glob('*.css'):
    if sheet.name != 'asset-manifest.css':
        used_variables.update(re.findall(r'var\((--asset-[\w-]+)\)', sheet.read_text()))
for source, variants in manifest.items():
    variable = '--asset-' + re.sub(r'[^a-zA-Z0-9-]', '-', source.removeprefix('assets/').removesuffix('.png'))
    if variable not in used_variables:
        continue
    css.append(f'  {variable}: url("{variants["full"]}");')
css.append('}')
(ROOT / 'asset-manifest.css').write_text('\n'.join(css) + '\n')
# Delete only obsolete output from this generator.
current = {ROOT / url for variants in manifest.values() for url in variants.values()}
for path in OUTPUT.glob('*.webp'):
    if path not in current:
        path.unlink()
print(f'{len(sources)} originals: {sum(p.stat().st_size for p in sources)/1024/1024:.2f} MiB')
print(f'{len(current)} web assets (including thumbnails): {sum(p.stat().st_size for p in current)/1024/1024:.2f} MiB')
